Vagrant.configure("2") do |config|
  config.vm.box = "lattice/ubuntu-trusty-64"
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file = "puppet.pp"
  end
end
